services:
  - type: web
    name: quickcheck-backend
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm install && npm install pg
    startCommand: npm start
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://inspectionapp-backend.onrender.com
      - key: DATABASE_TYPE
        value: postgresql
      - key: DATABASE_URL
        fromDatabase:
          name: quickcheck-db
          property: connectionString
    autoDeploy: true

databases:
  - name: quickcheck-db
    plan: starter
    databaseName: quickcheck
    user: quickcheck_user 